# Generated by Django 3.2.5 on 2021-09-26 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='piso',
            field=models.CharField(choices=[('Turmalina', 'TU'), ('Alejandro Ferrant 2', 'AF2'), ('Alejandro Ferrant 3', 'AF3'), ('Tomás Bretón', 'TB')], default='Turmalina', max_length=100),
        ),
    ]
