# Generated by Django 3.2.5 on 2021-09-26 14:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0002_item_piso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='item',
            name='box',
            field=models.IntegerField(verbose_name='Caja'),
        ),
        migrations.AlterField(
            model_name='item',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Publicación'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_name',
            field=models.CharField(max_length=100, verbose_name='Nombre de Artículo'),
        ),
        migrations.AlterField(
            model_name='item',
            name='piso',
            field=models.CharField(choices=[('Turmalina', 'TU'), ('Alejandro Ferrant 2', 'AF2'), ('Alejandro Ferrant 3', 'AF3'), ('Tomás Bretón', 'TB')], default='Turmalina', max_length=100, verbose_name='Piso'),
        ),
    ]
