# Generated by Django 3.2.5 on 2021-10-03 12:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0004_alter_item_item_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box_name', models.CharField(max_length=100, verbose_name='Nombre de la Caja')),
                ('box_number', models.IntegerField(verbose_name='Número de la Caja')),
                ('piso', models.CharField(choices=[('Turmalina', 'TU'), ('Alejandro Ferrant 2', 'AF2'), ('Alejandro Ferrant 3', 'AF3'), ('Tomás Bretón', 'TB')], default='Turmalina', max_length=100, verbose_name='Piso')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Creación')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
            ],
        ),
        migrations.AlterField(
            model_name='item',
            name='box',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.box', verbose_name='Caja'),
        ),
    ]
