# Generated by Django 3.2.5 on 2021-10-04 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20211003_1250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='piso',
        ),
    ]
