# Generated by Django 3.2.5 on 2021-10-04 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_remove_item_piso'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='box',
            unique_together={('box_number', 'piso')},
        ),
    ]
